# Meta data
name:         light7
authors:      任行
description:  Build mobile apps with simple HTML, CSS, and JS components.
favicon:      http://gtms04.alicdn.com/tps/i4/TB17MaDGpXXXXb7apXXAz6UFXXX-16-16.png
<<<<<<< HEAD
version:      0.1.0
=======
version:      0.2.0
>>>>>>> en/master

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
host:         0.0.0.0
port:         4000
